[package]
org = "ballerinax"
name = "editools"
version = "0.1.0"
distribution = "2201.4.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name= "edi"
version= "0.8.1"
repository= "local"